// AWS State Functions API Reference
// https://docs.amazonaws.cn/en_us/step-functions/latest/apireference/Welcome.html

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: skyflow.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommonService_Paging_FullMethodName = "/skyflow.CommonService/Paging"
	CommonService_HTTP_FullMethodName   = "/skyflow.CommonService/HTTP"
	CommonService_Ping_FullMethodName   = "/skyflow.CommonService/Ping"
)

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommonService 通用服务
type CommonServiceClient interface {
	// Paging 分页格式
	Paging(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error)
	// HTTPReturn  HTTP API接口返回值格式
	HTTP(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HTTPResponseMessage, error)
	// Ping ping service
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error)
}

type commonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonServiceClient(cc grpc.ClientConnInterface) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) Paging(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, CommonService_Paging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) HTTP(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HTTPResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponseMessage)
	err := c.cc.Invoke(ctx, CommonService_HTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, CommonService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServiceServer is the server API for CommonService service.
// All implementations must embed UnimplementedCommonServiceServer
// for forward compatibility.
//
// CommonService 通用服务
type CommonServiceServer interface {
	// Paging 分页格式
	Paging(context.Context, *PageRequest) (*PageResponse, error)
	// HTTPReturn  HTTP API接口返回值格式
	HTTP(context.Context, *emptypb.Empty) (*HTTPResponseMessage, error)
	// Ping ping service
	Ping(context.Context, *emptypb.Empty) (*PingResponse, error)
	mustEmbedUnimplementedCommonServiceServer()
}

// UnimplementedCommonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommonServiceServer struct{}

func (UnimplementedCommonServiceServer) Paging(context.Context, *PageRequest) (*PageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Paging not implemented")
}
func (UnimplementedCommonServiceServer) HTTP(context.Context, *emptypb.Empty) (*HTTPResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HTTP not implemented")
}
func (UnimplementedCommonServiceServer) Ping(context.Context, *emptypb.Empty) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCommonServiceServer) mustEmbedUnimplementedCommonServiceServer() {}
func (UnimplementedCommonServiceServer) testEmbeddedByValue()                       {}

// UnsafeCommonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonServiceServer will
// result in compilation errors.
type UnsafeCommonServiceServer interface {
	mustEmbedUnimplementedCommonServiceServer()
}

func RegisterCommonServiceServer(s grpc.ServiceRegistrar, srv CommonServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommonService_ServiceDesc, srv)
}

func _CommonService_Paging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).Paging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonService_Paging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).Paging(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_HTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).HTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonService_HTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).HTTP(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CommonService_ServiceDesc is the grpc.ServiceDesc for CommonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skyflow.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Paging",
			Handler:    _CommonService_Paging_Handler,
		},
		{
			MethodName: "HTTP",
			Handler:    _CommonService_HTTP_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CommonService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skyflow.proto",
}

const (
	SkyflowV1Service_CreateNamespace_FullMethodName                = "/skyflow.SkyflowV1Service/CreateNamespace"
	SkyflowV1Service_CreateOrUpdateNamespace_FullMethodName        = "/skyflow.SkyflowV1Service/CreateOrUpdateNamespace"
	SkyflowV1Service_ListNamespaces_FullMethodName                 = "/skyflow.SkyflowV1Service/ListNamespaces"
	SkyflowV1Service_DeleteNamespace_FullMethodName                = "/skyflow.SkyflowV1Service/DeleteNamespace"
	SkyflowV1Service_CreateActivity_FullMethodName                 = "/skyflow.SkyflowV1Service/CreateActivity"
	SkyflowV1Service_CreateOrUpdateActivity_FullMethodName         = "/skyflow.SkyflowV1Service/CreateOrUpdateActivity"
	SkyflowV1Service_ListActivities_FullMethodName                 = "/skyflow.SkyflowV1Service/ListActivities"
	SkyflowV1Service_DescribeActivity_FullMethodName               = "/skyflow.SkyflowV1Service/DescribeActivity"
	SkyflowV1Service_DeleteActivity_FullMethodName                 = "/skyflow.SkyflowV1Service/DeleteActivity"
	SkyflowV1Service_CreateStateMachine_FullMethodName             = "/skyflow.SkyflowV1Service/CreateStateMachine"
	SkyflowV1Service_CreateOrUpdateStateMachine_FullMethodName     = "/skyflow.SkyflowV1Service/CreateOrUpdateStateMachine"
	SkyflowV1Service_DeleteStateMachine_FullMethodName             = "/skyflow.SkyflowV1Service/DeleteStateMachine"
	SkyflowV1Service_ListStateMachines_FullMethodName              = "/skyflow.SkyflowV1Service/ListStateMachines"
	SkyflowV1Service_DescribeStateMachine_FullMethodName           = "/skyflow.SkyflowV1Service/DescribeStateMachine"
	SkyflowV1Service_UpdateStateMachine_FullMethodName             = "/skyflow.SkyflowV1Service/UpdateStateMachine"
	SkyflowV1Service_ParseStateMachine_FullMethodName              = "/skyflow.SkyflowV1Service/ParseStateMachine"
	SkyflowV1Service_ValidateStateMachineDefinition_FullMethodName = "/skyflow.SkyflowV1Service/ValidateStateMachineDefinition"
	SkyflowV1Service_StartExecution_FullMethodName                 = "/skyflow.SkyflowV1Service/StartExecution"
	SkyflowV1Service_DescribeExecution_FullMethodName              = "/skyflow.SkyflowV1Service/DescribeExecution"
	SkyflowV1Service_DescribeExecutionBone_FullMethodName          = "/skyflow.SkyflowV1Service/DescribeExecutionBone"
	SkyflowV1Service_StopExecution_FullMethodName                  = "/skyflow.SkyflowV1Service/StopExecution"
	SkyflowV1Service_ListExecutions_FullMethodName                 = "/skyflow.SkyflowV1Service/ListExecutions"
	SkyflowV1Service_ListExecutionEvents_FullMethodName            = "/skyflow.SkyflowV1Service/ListExecutionEvents"
	SkyflowV1Service_DescribeStep_FullMethodName                   = "/skyflow.SkyflowV1Service/DescribeStep"
	SkyflowV1Service_ListStepEvents_FullMethodName                 = "/skyflow.SkyflowV1Service/ListStepEvents"
	SkyflowV1Service_GetActivityTask_FullMethodName                = "/skyflow.SkyflowV1Service/GetActivityTask"
)

// SkyflowV1ServiceClient is the client API for SkyflowV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SkyflowV1Service workflow Service
type SkyflowV1ServiceClient interface {
	// CreateNamespace 创建一个命名空间
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	// CreateOrUpdateNamespace 创建/更新一个命名空间
	CreateOrUpdateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	// ListNamespaces 获得命名空间列表
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	// DeleteNamespace 删除一个命名空间
	// 注意: 只有当命名空间下没有任何活动和状态机时，才能删除命名空间
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CreateActivity 创建一个活动
	CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*CreateActivityResponse, error)
	// CreateOrUpdateActivity 创建/更新一个活动
	CreateOrUpdateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*CreateActivityResponse, error)
	// ListActivities 获得活动列表
	ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
	// DescribeActivity 获得一个活动的描述
	DescribeActivity(ctx context.Context, in *DescribeActivityRequest, opts ...grpc.CallOption) (*DescribeActivityResponse, error)
	// DeleteActivity 删除一个活动
	DeleteActivity(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityResponse, error)
	// CreateStateMachine 创建一个状态机
	CreateStateMachine(ctx context.Context, in *CreateStateMachineRequest, opts ...grpc.CallOption) (*CreateStateMachineResponse, error)
	// CreateOrUpdateStateMachine 创建/更新一个状态机
	CreateOrUpdateStateMachine(ctx context.Context, in *CreateStateMachineRequest, opts ...grpc.CallOption) (*CreateStateMachineResponse, error)
	// DeleteStateMachine 删除一个状态机
	DeleteStateMachine(ctx context.Context, in *DeleteStateMachineRequest, opts ...grpc.CallOption) (*DeleteStateMachineResponse, error)
	// ListStateMachines 获得状态机列表
	ListStateMachines(ctx context.Context, in *ListStateMachinesRequest, opts ...grpc.CallOption) (*ListStateMachinesResponse, error)
	// DescribeStateMachine 获得一个状态机的描述
	DescribeStateMachine(ctx context.Context, in *DescribeStateMachineRequest, opts ...grpc.CallOption) (*DescribeStateMachineResponse, error)
	// UpdateStateMachine 更新一个状态机
	UpdateStateMachine(ctx context.Context, in *UpdateStateMachineRequest, opts ...grpc.CallOption) (*UpdateStateMachineResponse, error)
	// ParseStateMachine 解析一个状态机模板，返回解析后的定义和类型
	// 验证definition的合法性
	ParseStateMachine(ctx context.Context, in *ParseStateMachineRequest, opts ...grpc.CallOption) (*ParseStateMachineResponse, error)
	// ValidateStateMachineDefinition 验证状态机定义的合法性
	ValidateStateMachineDefinition(ctx context.Context, in *ValidateStateMachineDefinitionRequest, opts ...grpc.CallOption) (*ValidateStateMachineDefinitionResponse, error)
	// 任务管理
	// StartExecution 创建一个执行任务
	StartExecution(ctx context.Context, in *StartExecutionRequest, opts ...grpc.CallOption) (*StartExecutionResponse, error)
	// DescribeExecution 获得一个执行的描述
	DescribeExecution(ctx context.Context, in *DescribeExecutionRequest, opts ...grpc.CallOption) (*DescribeExecutionResponse, error)
	// DescribeExecutionBone 获得一个执行的执行的Bone信息
	// Bone信息用于前段展示执行的流程图
	DescribeExecutionBone(ctx context.Context, in *DescribeExecutionBoneRequest, opts ...grpc.CallOption) (*DescribeExecutionBoneResponse, error)
	// StopExecution 终止一个执行
	StopExecution(ctx context.Context, in *StopExecutionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListExecutions 获得execution列表
	ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error)
	// ListExecutionEvents 获得一个执行的Event列表
	ListExecutionEvents(ctx context.Context, in *ListExecutionEventsRequest, opts ...grpc.CallOption) (*ListExecutionEventsResponse, error)
	DescribeStep(ctx context.Context, in *DescribeStepRequest, opts ...grpc.CallOption) (*DescribeStepResponse, error)
	ListStepEvents(ctx context.Context, in *ListStepEventsRequest, opts ...grpc.CallOption) (*ListExecutionEventsResponse, error)
	GetActivityTask(ctx context.Context, in *GetActivityTaskRequest, opts ...grpc.CallOption) (*GetActivityTaskResponse, error)
}

type skyflowV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkyflowV1ServiceClient(cc grpc.ClientConnInterface) SkyflowV1ServiceClient {
	return &skyflowV1ServiceClient{cc}
}

func (c *skyflowV1ServiceClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_CreateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) CreateOrUpdateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_CreateOrUpdateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DeleteNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*CreateActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateActivityResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) CreateOrUpdateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*CreateActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateActivityResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_CreateOrUpdateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ListActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DescribeActivity(ctx context.Context, in *DescribeActivityRequest, opts ...grpc.CallOption) (*DescribeActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeActivityResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DescribeActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DeleteActivity(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteActivityResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DeleteActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) CreateStateMachine(ctx context.Context, in *CreateStateMachineRequest, opts ...grpc.CallOption) (*CreateStateMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStateMachineResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_CreateStateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) CreateOrUpdateStateMachine(ctx context.Context, in *CreateStateMachineRequest, opts ...grpc.CallOption) (*CreateStateMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStateMachineResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_CreateOrUpdateStateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DeleteStateMachine(ctx context.Context, in *DeleteStateMachineRequest, opts ...grpc.CallOption) (*DeleteStateMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStateMachineResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DeleteStateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ListStateMachines(ctx context.Context, in *ListStateMachinesRequest, opts ...grpc.CallOption) (*ListStateMachinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStateMachinesResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ListStateMachines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DescribeStateMachine(ctx context.Context, in *DescribeStateMachineRequest, opts ...grpc.CallOption) (*DescribeStateMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeStateMachineResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DescribeStateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) UpdateStateMachine(ctx context.Context, in *UpdateStateMachineRequest, opts ...grpc.CallOption) (*UpdateStateMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStateMachineResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_UpdateStateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ParseStateMachine(ctx context.Context, in *ParseStateMachineRequest, opts ...grpc.CallOption) (*ParseStateMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseStateMachineResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ParseStateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ValidateStateMachineDefinition(ctx context.Context, in *ValidateStateMachineDefinitionRequest, opts ...grpc.CallOption) (*ValidateStateMachineDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateStateMachineDefinitionResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ValidateStateMachineDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) StartExecution(ctx context.Context, in *StartExecutionRequest, opts ...grpc.CallOption) (*StartExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartExecutionResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_StartExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DescribeExecution(ctx context.Context, in *DescribeExecutionRequest, opts ...grpc.CallOption) (*DescribeExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeExecutionResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DescribeExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DescribeExecutionBone(ctx context.Context, in *DescribeExecutionBoneRequest, opts ...grpc.CallOption) (*DescribeExecutionBoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeExecutionBoneResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DescribeExecutionBone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) StopExecution(ctx context.Context, in *StopExecutionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SkyflowV1Service_StopExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ListExecutionEvents(ctx context.Context, in *ListExecutionEventsRequest, opts ...grpc.CallOption) (*ListExecutionEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionEventsResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ListExecutionEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) DescribeStep(ctx context.Context, in *DescribeStepRequest, opts ...grpc.CallOption) (*DescribeStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeStepResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_DescribeStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) ListStepEvents(ctx context.Context, in *ListStepEventsRequest, opts ...grpc.CallOption) (*ListExecutionEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionEventsResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_ListStepEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyflowV1ServiceClient) GetActivityTask(ctx context.Context, in *GetActivityTaskRequest, opts ...grpc.CallOption) (*GetActivityTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivityTaskResponse)
	err := c.cc.Invoke(ctx, SkyflowV1Service_GetActivityTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkyflowV1ServiceServer is the server API for SkyflowV1Service service.
// All implementations must embed UnimplementedSkyflowV1ServiceServer
// for forward compatibility.
//
// SkyflowV1Service workflow Service
type SkyflowV1ServiceServer interface {
	// CreateNamespace 创建一个命名空间
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	// CreateOrUpdateNamespace 创建/更新一个命名空间
	CreateOrUpdateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	// ListNamespaces 获得命名空间列表
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	// DeleteNamespace 删除一个命名空间
	// 注意: 只有当命名空间下没有任何活动和状态机时，才能删除命名空间
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*emptypb.Empty, error)
	// CreateActivity 创建一个活动
	CreateActivity(context.Context, *CreateActivityRequest) (*CreateActivityResponse, error)
	// CreateOrUpdateActivity 创建/更新一个活动
	CreateOrUpdateActivity(context.Context, *CreateActivityRequest) (*CreateActivityResponse, error)
	// ListActivities 获得活动列表
	ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error)
	// DescribeActivity 获得一个活动的描述
	DescribeActivity(context.Context, *DescribeActivityRequest) (*DescribeActivityResponse, error)
	// DeleteActivity 删除一个活动
	DeleteActivity(context.Context, *DeleteActivityRequest) (*DeleteActivityResponse, error)
	// CreateStateMachine 创建一个状态机
	CreateStateMachine(context.Context, *CreateStateMachineRequest) (*CreateStateMachineResponse, error)
	// CreateOrUpdateStateMachine 创建/更新一个状态机
	CreateOrUpdateStateMachine(context.Context, *CreateStateMachineRequest) (*CreateStateMachineResponse, error)
	// DeleteStateMachine 删除一个状态机
	DeleteStateMachine(context.Context, *DeleteStateMachineRequest) (*DeleteStateMachineResponse, error)
	// ListStateMachines 获得状态机列表
	ListStateMachines(context.Context, *ListStateMachinesRequest) (*ListStateMachinesResponse, error)
	// DescribeStateMachine 获得一个状态机的描述
	DescribeStateMachine(context.Context, *DescribeStateMachineRequest) (*DescribeStateMachineResponse, error)
	// UpdateStateMachine 更新一个状态机
	UpdateStateMachine(context.Context, *UpdateStateMachineRequest) (*UpdateStateMachineResponse, error)
	// ParseStateMachine 解析一个状态机模板，返回解析后的定义和类型
	// 验证definition的合法性
	ParseStateMachine(context.Context, *ParseStateMachineRequest) (*ParseStateMachineResponse, error)
	// ValidateStateMachineDefinition 验证状态机定义的合法性
	ValidateStateMachineDefinition(context.Context, *ValidateStateMachineDefinitionRequest) (*ValidateStateMachineDefinitionResponse, error)
	// 任务管理
	// StartExecution 创建一个执行任务
	StartExecution(context.Context, *StartExecutionRequest) (*StartExecutionResponse, error)
	// DescribeExecution 获得一个执行的描述
	DescribeExecution(context.Context, *DescribeExecutionRequest) (*DescribeExecutionResponse, error)
	// DescribeExecutionBone 获得一个执行的执行的Bone信息
	// Bone信息用于前段展示执行的流程图
	DescribeExecutionBone(context.Context, *DescribeExecutionBoneRequest) (*DescribeExecutionBoneResponse, error)
	// StopExecution 终止一个执行
	StopExecution(context.Context, *StopExecutionRequest) (*emptypb.Empty, error)
	// ListExecutions 获得execution列表
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	// ListExecutionEvents 获得一个执行的Event列表
	ListExecutionEvents(context.Context, *ListExecutionEventsRequest) (*ListExecutionEventsResponse, error)
	DescribeStep(context.Context, *DescribeStepRequest) (*DescribeStepResponse, error)
	ListStepEvents(context.Context, *ListStepEventsRequest) (*ListExecutionEventsResponse, error)
	GetActivityTask(context.Context, *GetActivityTaskRequest) (*GetActivityTaskResponse, error)
	mustEmbedUnimplementedSkyflowV1ServiceServer()
}

// UnimplementedSkyflowV1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkyflowV1ServiceServer struct{}

func (UnimplementedSkyflowV1ServiceServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) CreateOrUpdateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateNamespace not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) CreateActivity(context.Context, *CreateActivityRequest) (*CreateActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) CreateOrUpdateActivity(context.Context, *CreateActivityRequest) (*CreateActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateActivity not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DescribeActivity(context.Context, *DescribeActivityRequest) (*DescribeActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeActivity not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DeleteActivity(context.Context, *DeleteActivityRequest) (*DeleteActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteActivity not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) CreateStateMachine(context.Context, *CreateStateMachineRequest) (*CreateStateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStateMachine not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) CreateOrUpdateStateMachine(context.Context, *CreateStateMachineRequest) (*CreateStateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateStateMachine not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DeleteStateMachine(context.Context, *DeleteStateMachineRequest) (*DeleteStateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStateMachine not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ListStateMachines(context.Context, *ListStateMachinesRequest) (*ListStateMachinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStateMachines not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DescribeStateMachine(context.Context, *DescribeStateMachineRequest) (*DescribeStateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeStateMachine not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) UpdateStateMachine(context.Context, *UpdateStateMachineRequest) (*UpdateStateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStateMachine not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ParseStateMachine(context.Context, *ParseStateMachineRequest) (*ParseStateMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseStateMachine not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ValidateStateMachineDefinition(context.Context, *ValidateStateMachineDefinitionRequest) (*ValidateStateMachineDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStateMachineDefinition not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) StartExecution(context.Context, *StartExecutionRequest) (*StartExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartExecution not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DescribeExecution(context.Context, *DescribeExecutionRequest) (*DescribeExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeExecution not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DescribeExecutionBone(context.Context, *DescribeExecutionBoneRequest) (*DescribeExecutionBoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeExecutionBone not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) StopExecution(context.Context, *StopExecutionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopExecution not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ListExecutionEvents(context.Context, *ListExecutionEventsRequest) (*ListExecutionEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExecutionEvents not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) DescribeStep(context.Context, *DescribeStepRequest) (*DescribeStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeStep not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) ListStepEvents(context.Context, *ListStepEventsRequest) (*ListExecutionEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStepEvents not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) GetActivityTask(context.Context, *GetActivityTaskRequest) (*GetActivityTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityTask not implemented")
}
func (UnimplementedSkyflowV1ServiceServer) mustEmbedUnimplementedSkyflowV1ServiceServer() {}
func (UnimplementedSkyflowV1ServiceServer) testEmbeddedByValue()                          {}

// UnsafeSkyflowV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkyflowV1ServiceServer will
// result in compilation errors.
type UnsafeSkyflowV1ServiceServer interface {
	mustEmbedUnimplementedSkyflowV1ServiceServer()
}

func RegisterSkyflowV1ServiceServer(s grpc.ServiceRegistrar, srv SkyflowV1ServiceServer) {
	// If the following call pancis, it indicates UnimplementedSkyflowV1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkyflowV1Service_ServiceDesc, srv)
}

func _SkyflowV1Service_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_CreateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_CreateOrUpdateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).CreateOrUpdateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_CreateOrUpdateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).CreateOrUpdateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DeleteNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).CreateActivity(ctx, req.(*CreateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_CreateOrUpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).CreateOrUpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_CreateOrUpdateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).CreateOrUpdateActivity(ctx, req.(*CreateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ListActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ListActivities(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DescribeActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DescribeActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DescribeActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DescribeActivity(ctx, req.(*DescribeActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DeleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DeleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DeleteActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DeleteActivity(ctx, req.(*DeleteActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_CreateStateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).CreateStateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_CreateStateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).CreateStateMachine(ctx, req.(*CreateStateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_CreateOrUpdateStateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).CreateOrUpdateStateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_CreateOrUpdateStateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).CreateOrUpdateStateMachine(ctx, req.(*CreateStateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DeleteStateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DeleteStateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DeleteStateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DeleteStateMachine(ctx, req.(*DeleteStateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ListStateMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStateMachinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ListStateMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ListStateMachines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ListStateMachines(ctx, req.(*ListStateMachinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DescribeStateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeStateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DescribeStateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DescribeStateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DescribeStateMachine(ctx, req.(*DescribeStateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_UpdateStateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).UpdateStateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_UpdateStateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).UpdateStateMachine(ctx, req.(*UpdateStateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ParseStateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseStateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ParseStateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ParseStateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ParseStateMachine(ctx, req.(*ParseStateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ValidateStateMachineDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStateMachineDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ValidateStateMachineDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ValidateStateMachineDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ValidateStateMachineDefinition(ctx, req.(*ValidateStateMachineDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_StartExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).StartExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_StartExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).StartExecution(ctx, req.(*StartExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DescribeExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DescribeExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DescribeExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DescribeExecution(ctx, req.(*DescribeExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DescribeExecutionBone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeExecutionBoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DescribeExecutionBone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DescribeExecutionBone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DescribeExecutionBone(ctx, req.(*DescribeExecutionBoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_StopExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).StopExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_StopExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).StopExecution(ctx, req.(*StopExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ListExecutions(ctx, req.(*ListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ListExecutionEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ListExecutionEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ListExecutionEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ListExecutionEvents(ctx, req.(*ListExecutionEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_DescribeStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).DescribeStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_DescribeStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).DescribeStep(ctx, req.(*DescribeStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_ListStepEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStepEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).ListStepEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_ListStepEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).ListStepEvents(ctx, req.(*ListStepEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyflowV1Service_GetActivityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyflowV1ServiceServer).GetActivityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyflowV1Service_GetActivityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyflowV1ServiceServer).GetActivityTask(ctx, req.(*GetActivityTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkyflowV1Service_ServiceDesc is the grpc.ServiceDesc for SkyflowV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkyflowV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skyflow.SkyflowV1Service",
	HandlerType: (*SkyflowV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _SkyflowV1Service_CreateNamespace_Handler,
		},
		{
			MethodName: "CreateOrUpdateNamespace",
			Handler:    _SkyflowV1Service_CreateOrUpdateNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _SkyflowV1Service_ListNamespaces_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _SkyflowV1Service_DeleteNamespace_Handler,
		},
		{
			MethodName: "CreateActivity",
			Handler:    _SkyflowV1Service_CreateActivity_Handler,
		},
		{
			MethodName: "CreateOrUpdateActivity",
			Handler:    _SkyflowV1Service_CreateOrUpdateActivity_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _SkyflowV1Service_ListActivities_Handler,
		},
		{
			MethodName: "DescribeActivity",
			Handler:    _SkyflowV1Service_DescribeActivity_Handler,
		},
		{
			MethodName: "DeleteActivity",
			Handler:    _SkyflowV1Service_DeleteActivity_Handler,
		},
		{
			MethodName: "CreateStateMachine",
			Handler:    _SkyflowV1Service_CreateStateMachine_Handler,
		},
		{
			MethodName: "CreateOrUpdateStateMachine",
			Handler:    _SkyflowV1Service_CreateOrUpdateStateMachine_Handler,
		},
		{
			MethodName: "DeleteStateMachine",
			Handler:    _SkyflowV1Service_DeleteStateMachine_Handler,
		},
		{
			MethodName: "ListStateMachines",
			Handler:    _SkyflowV1Service_ListStateMachines_Handler,
		},
		{
			MethodName: "DescribeStateMachine",
			Handler:    _SkyflowV1Service_DescribeStateMachine_Handler,
		},
		{
			MethodName: "UpdateStateMachine",
			Handler:    _SkyflowV1Service_UpdateStateMachine_Handler,
		},
		{
			MethodName: "ParseStateMachine",
			Handler:    _SkyflowV1Service_ParseStateMachine_Handler,
		},
		{
			MethodName: "ValidateStateMachineDefinition",
			Handler:    _SkyflowV1Service_ValidateStateMachineDefinition_Handler,
		},
		{
			MethodName: "StartExecution",
			Handler:    _SkyflowV1Service_StartExecution_Handler,
		},
		{
			MethodName: "DescribeExecution",
			Handler:    _SkyflowV1Service_DescribeExecution_Handler,
		},
		{
			MethodName: "DescribeExecutionBone",
			Handler:    _SkyflowV1Service_DescribeExecutionBone_Handler,
		},
		{
			MethodName: "StopExecution",
			Handler:    _SkyflowV1Service_StopExecution_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _SkyflowV1Service_ListExecutions_Handler,
		},
		{
			MethodName: "ListExecutionEvents",
			Handler:    _SkyflowV1Service_ListExecutionEvents_Handler,
		},
		{
			MethodName: "DescribeStep",
			Handler:    _SkyflowV1Service_DescribeStep_Handler,
		},
		{
			MethodName: "ListStepEvents",
			Handler:    _SkyflowV1Service_ListStepEvents_Handler,
		},
		{
			MethodName: "GetActivityTask",
			Handler:    _SkyflowV1Service_GetActivityTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skyflow.proto",
}
