// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: skyflow.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSkyflowV1ServiceCreateNamespace = "/skyflow.SkyflowV1Service/CreateNamespace"

type SkyflowV1ServiceHTTPServer interface {
	// CreateNamespace CreateNamespace 创建一个命名空间
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
}

func RegisterSkyflowV1ServiceHTTPServer(s *http.Server, srv SkyflowV1ServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/CreateNamespace", _SkyflowV1Service_CreateNamespace0_HTTP_Handler(srv))
}

func _SkyflowV1Service_CreateNamespace0_HTTP_Handler(srv SkyflowV1ServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNamespaceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkyflowV1ServiceCreateNamespace)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNamespace(ctx, req.(*CreateNamespaceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNamespaceResponse)
		return ctx.Result(200, reply)
	}
}

type SkyflowV1ServiceHTTPClient interface {
	// CreateNamespace CreateNamespace 创建一个命名空间
	CreateNamespace(ctx context.Context, req *CreateNamespaceRequest, opts ...http.CallOption) (rsp *CreateNamespaceResponse, err error)
}

type SkyflowV1ServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSkyflowV1ServiceHTTPClient(client *http.Client) SkyflowV1ServiceHTTPClient {
	return &SkyflowV1ServiceHTTPClientImpl{client}
}

// CreateNamespace CreateNamespace 创建一个命名空间
func (c *SkyflowV1ServiceHTTPClientImpl) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...http.CallOption) (*CreateNamespaceResponse, error) {
	var out CreateNamespaceResponse
	pattern := "/api/v1/CreateNamespace"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSkyflowV1ServiceCreateNamespace))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
