@hostname = 127.0.0.1
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = application/json


### StartExecution
POST  {{host}}/api/v1/StartExecution
Content-Type: {{contentType}}

{
  "statemachine_uri": "statemachine:example-namespace/example-state-machine"
  
}


### StopExecution
POST  {{host}}/api/v1/StopExecution
Content-Type: {{contentType}}

{
  "title": "example-execution",
  "statemachine_uri": "statemachine://example-statemachine"
}

### CreateNamespace
POST  {{host}}/api/v1/CreateNamespace
Content-Type: {{contentType}}

{
  "name": "example-namespace",
  "description": "This is a namespace to test the functionality"
}