@hostname = 127.0.0.1
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = application/json


### StartExecution
POST  {{host}}/api/v1/StartExecution
Content-Type: {{contentType}}

{
  "statemachine_uri": "statemachine:example-namespace/example-state-machine"

}


### DescribeExecution
POST  {{host}}/api/v1/DescribeExecution
Content-Type: {{contentType}}

{
  "execution_uuid": "18d1b2cf-4013-4866-baae-9822e026fc3d"
}

### StopExecution
POST  {{host}}/api/v1/StopExecution
Content-Type: {{contentType}}

{
  "title": "example-execution",
  "statemachine_uri": "statemachine://example-statemachine"
}

### CreateNamespace
POST  {{host}}/api/v1/GetActivityTask
Content-Type: {{contentType}}

{
  "activity_uri": "activity:unittest/Testadd111"
}


### SendTaskSuccess
POST {{host}}/api/v1/SendTaskSuccess
Content-Type: {{contentType}}


{
  "task_token": "",
  "output": ""
}

### DescribeExecutionBone
POST {{host}}/api/v1/DescribeExecutionBone
Content-Type: {{contentType}}

{
  "execution_uuid": "980ea130-df8e-40ff-8eb0-f3e25ccfa9d9"
}