# @hostname = 127.0.0.1
# @port = 8080
@host = http://127.0.0.1:8080
@contentType = application/json


### CreateNamespace
POST  {{host}}/api/v1/CreateNamespace
Content-Type: {{contentType}}

{
  "name": "example-namespace",
  "description": "This is a namespace to test the functionality"

}

### CreateNamespace
POST  {{host}}/api/v1/CreateOrUpdateNamespace
Content-Type: {{contentType}}

{
  "name": "example-create-update-namespace",
  "description": "This is a namespace to test the create or update functionality"

}


### ListNamespaces
POST  {{host}}/api/v1/ListNamespaces
Content-Type: {{contentType}}

{
    "page_request": {
        "page_size": 120,
        "page_number": 1
    }
}

### DeleteNamespace
POST  {{host}}/api/v1/DeleteNamespace
Content-Type: {{contentType}}

{
  "name": "example-namespace"
}


### CreateOrUpdateActivity
POST  {{host}}/api/v1/CreateOrUpdateActivity
Content-Type: application/json

{
  "namespace": "example-namespace",
  "activity_id": "activity-1",
  "name": "Example Activity",
  "description": "This is an example activity",
  "start_time": "2023-10-01T00:00:00Z",
  "end_time": "2023-10-02T00:00:00Z"
}

### CreateOrUpdateActivity
POST  {{host}}/api/v1/CreateOrUpdateActivity
Content-Type: application/json

{
  "namespace": "example-namespace",
  "activity_id": "activity-2",
  "name": "Example Activity2",
  "description": "This is an example activity2",
  "start_time": "2023-10-01T00:00:00Z",
  "end_time": "2023-10-02T00:00:00Z"
}



### ListActivities
POST  {{host}}/api/v1/ListActivities
Content-Type: application/json

{
    "namespace": "example-namespace"
}


### GetEvents
POST {{host}}/api/v1/ListActivities
Content-Type: application/json

{
    "namespace": "namespace"
}

### CreateStateMachine
POST  {{host}}/api/v1/CreateStateMachine
Content-Type: {{contentType}}

{
  "name": "example-state-machine",
  "description": "This is a state machine to test the functionality",
  "namespace": "example-namespace",
  "definition": "{\"StartAt\":\"Hello\",\"States\":{\"Hello\":{\"Type\":\"Pass\",\"Result\":{\"message\":\"Hello World\"}, \"End\":true}}}"
}


### ParseStateMachine
POST  {{host}}/api/v1/ParseStateMachine
Content-Type: {{contentType}}

{
  "definition": "{\"StartAt\":\"Hello\",\"States\":{\"Hello\":{\"Type\":\"Pass\",\"Result\":{\"message\":\"Hello World\"}, \"End\":true}}}"
}



### ParseStateMachine
POST  {{host}}/api/v1/ParseStateMachine
Content-Type: {{contentType}}

{
    "definition": "{\"Comment\": \"testactivity \", \"Type\": \"statemachine\", \"Version\": \"1.0\", \"StartAt\": \"S1\", \"States\": {\"S1\": {\"Type\": \"Task\", \"Parameters\": {\"x.$\": \"$.x\", \"y.$\": \"$.y\"}, \"Resource\": \"activity:unittest/Testadd\", \"ResultPath\": \"$.z\", \"TimeoutSeconds\": 600, \"HeartbeatSeconds\": 60, \"Next\": \"S2\"}, \"S2\": {\"Type\": \"Task\", \"Parameters\": {\"x.$\": \"$.x\", \"y.$\": \"$.z\"}, \"Resource\": \"activity:unittest/Testadd\", \"ResultPath\": \"$.z\", \"Next\": \"S3\"}, \"S3\": {\"Type\": \"Task\", \"Parameters\": {\"x.$\": \"$.x\", \"y.$\": \"$.z\"}, \"Resource\": \"activity:unittest/TestaddActivity2\", \"Next\": \"S4\"}, \"S4\": {\"Type\": \"Pass\", \"Resource\": \"activity:unittest/TestaddActivity2\", \"Result\": {}, \"End\": true}}}"
}

### ListStateMachines
POST  {{host}}/api/v1/ListStateMachines
Content-Type: application/json

{
    "namespace": "example-namespace"
}

### ListActivities
POST {{host}}/api/v1/ListActivities
Content-Type: application/json

{
    "namespace": "example-namespace"
}